### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mre**

### CODE REVIEW

**Comment by Hoverbear** [comment]
Oh dear me. Thanks for doing this. :-) I really appreciate this.

**Comment by mre** [comment]
You're welcome. :smile: Awesome blog post by the way!

**Comment by Hoverbear** [comment]
Thank you! It was originally written as a conference paper hence the briefness of some topics. Did you have any topics you'd like to read about?

**Comment by mre** [comment]
Oh! I'm humbled that you ask me :sparkles: 

Well I've seen that you run a rust-rosetta project. Maybe you find the time to write about common design patterns that you use when writing Rust code. Something like "Idiomatic Rust" or so. That would greatly help newcomers like myself. I'm thinking about a list of quick tips with little examples.

In your "Understanding Over Guesswork" post you were also mentioning thread safety. Would be cool if you could elaborate a bit. Like giving an example where Rust currently isn't thread safe and why.

Since I'm at it, I'd also like to get your opinion on the heartbleed debate: https://tonyarcieri.com/would-rust-have-prevented-heartbleed-another-look. So how does Rust prevent bugs like this and are there still some edge cases?

Keep in mind, all of this is completely up to you. I'm super happy just to follow along. Thanks for taking the time to educate beginners. I'm sure you'll do great after finishing your studies. :smiley:

**Comment by Hoverbear** [comment]
I've been thinking about doing a post on Rust Idioms actually! Glad to see there is interest. Perhaps that will be my first article after this insane month is over. :)

I think what a lot of people forget is that there are ways in Rust you can blatantly circumvent memory/type safety in Rust too, just as in OpenSSL, it's just Rust really discourages you from doing it and makes it hard. I don't think Rust **will** prevent these (because someone will inevitably take the 'easy' way out), but I think, if used as is intended, it **can**. But the same could be said for any language.

Talking about where it starts to break down is well covered in the [Rustonomicon](https://doc.rust-lang.org/nomicon/) :)

**Comment by mre** [comment]
Cool! Looking forward to that post on Rust Idioms. Would definitely read it. But first of all, don't feel pressured to deliver anything. :)

**Pull request merged**
